import Head from "next/head";
import { File as FileIcon } from "react-feather";

export default function Home() {
    return (
        <div>
            <Head>
                <title>File Transfer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="w-full h-screen bg-gray-50 p-10">
                <div className="container w-4/5 h-3/5 bg-cyan-100 rounded-3xl mx-auto relative">
                    <div className="title text-center pt-20">
                        <h1 className="text-5xl text-blue-900 font-bold">
                            Transfer Files to anyone
                        </h1>
                    </div>
                    <div
                        id="input-container"
                        className=" w-1/2 rounded-3xl mx-auto bg-white shadow-md hover:shadow-lg transition-all p-4"
                    >
                        <label
                            htmlFor=""
                            className="h-full w-full p-2 text-blue-900  items-center justify-center border-cyan-100 border-4 rounded-3xl border-dotted flex flex-col"
                        >
                            <p className="text-xl ">Drag and drop your file to upload</p>
                            <button className="outline-none border-2 border-cyan-100 p-2 rounded-lg my-2">Browse Files</button>
                            <FileIcon height={30} width={30} className={"mt-4"} />
                        </label>
                    </div>
                </div>
            </main>
        </div>
    );
}
